# Generated by Django 3.2.3 on 2021-12-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
