# Generated by Django 4.0 on 2021-12-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='origins/'),
        ),
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
