# Generated by Django 3.2.3 on 2021-12-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211219_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
